# Generated by gencrud
# field serie.IS_ENABLED constants
C_IS_ENABLED_YES                                                = True
C_IS_ENABLED_NO                                                 = False

C_IS_ENABLED_MAPPING = {True: 'Yes', False: 'No'}


