# Generated by gencrud
# field movie.IM_ENABLED constants
C_IM_ENABLED_YES                                                = True
C_IM_ENABLED_NO                                                 = False

C_IM_ENABLED_MAPPING = {True: 'Yes', False: 'No'}


