# Generated by gencrud
# field role_access.RA_CREATE constants

C_RA_CREATE_MAPPING = {True: 'Yes', False: 'No'}


# field role_access.RA_READ constants

C_RA_READ_MAPPING = {True: 'Yes', False: 'No'}


# field role_access.RA_UPDATE constants

C_RA_UPDATE_MAPPING = {True: 'Yes', False: 'No'}


# field role_access.RA_DELETE constants

C_RA_DELETE_MAPPING = {True: 'Yes', False: 'No'}


