#
#   Python backend and Angular frontend code generation by gencrud
#   Copyright (C) 2018-2021 Marc Bertens-Nguyen m.bertens@pe2mbs.nl
#
#   This library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU Library General Public License GPL-2.0-only
#   as published by the Free Software Foundation.
#
#   This library is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Library General Public License for more details.
#
#   You should have received a copy of the GNU Library General Public
#   License GPL-2.0-only along with this library; if not, write to the
#   Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#   Boston, MA 02110-1301 USA
#
#   gencrud: 2021-04-04 08:27:09 version 2.1.680 by user mbertens
#
import webapp2.api as API
from marshmallow import fields, pre_load, post_dump
from webapp2.common.convert import value2Label, utcDateString2Local


class RoleAccessSchema( API.mm.SQLAlchemySchema ):
    """Schema for the role_access table, this is generated by the gencrud.py module
    When modifing the file make sure that you remove the table from the configuration.
    """
    RA_ID    = fields.Integer()
    RA_R_ID    = fields.Integer()
    RA_R_ID_FK              = API.mm.Nested( 'RoleSchema' )
    RA_MA_ID    = fields.Integer()
    RA_MA_ID_FK             = API.mm.Nested( 'ModuleAccessSchema' )
    RA_CREATE    = fields.Boolean()
    RA_READ    = fields.Boolean()
    RA_UPDATE    = fields.Boolean()
    RA_DELETE    = fields.Boolean()
    R_REMARK    = fields.String()

    @post_dump
    def post_dump_process( self, in_data, **kwargs ):
        in_data[ 'RA_CREATE_LABEL' ] = value2Label( {True: 'Yes', False: 'No'}, in_data[ 'RA_CREATE' ] )
        in_data[ 'RA_READ_LABEL' ] = value2Label( {True: 'Yes', False: 'No'}, in_data[ 'RA_READ' ] )
        in_data[ 'RA_UPDATE_LABEL' ] = value2Label( {True: 'Yes', False: 'No'}, in_data[ 'RA_UPDATE' ] )
        in_data[ 'RA_DELETE_LABEL' ] = value2Label( {True: 'Yes', False: 'No'}, in_data[ 'RA_DELETE' ] )
        return in_data

    @pre_load
    def pre_load_process( self, out_data, **kwargs ):
        return out_data


role_accessSchema   = RoleAccessSchema()
role_accesssSchema  = RoleAccessSchema( many = True )

