# Generated by gencrud
# field news.N_ACTIVE constants
C_N_ACTIVE_YES                                                = True
C_N_ACTIVE_NO                                                 = False

C_N_ACTIVE_MAPPING = {True: 'Yes', False: 'No'}


# field news.N_ALERT constants
C_N_ALERT_YES                                                = True
C_N_ALERT_NO                                                 = False

C_N_ALERT_MAPPING = {True: 'Yes', False: 'No'}


# field news.N_KEEP constants
C_N_KEEP_YES                                                = True
C_N_KEEP_NO                                                 = False

C_N_KEEP_MAPPING = {True: 'Yes', False: 'No'}


