#
#   Python backend and Angular frontend code generation by gencrud
#   Copyright (C) 2018-2021 Marc Bertens-Nguyen m.bertens@pe2mbs.nl
#
#   This library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU Library General Public License GPL-2.0-only
#   as published by the Free Software Foundation.
#
#   This library is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Library General Public License for more details.
#
#   You should have received a copy of the GNU Library General Public
#   License GPL-2.0-only along with this library; if not, write to the
#   Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#   Boston, MA 02110-1301 USA
#
#   gencrud: 2022-04-10 21:02:18 version 3.0.685 by user mbertens
#
import webapp2.api as API
from webapp2.common.dbmem import DbBaseMemory
from webapp2.common.crudmixin import CrudModelMixin




class Episode( API.db.Model, CrudModelMixin ):
    """Model for the episode table, this is generated by the gencrud.py module
    When modifing the file make sure that you remove the table from the configuration.
    """
    __field_list__       = ['IE_ID', 'IE_NAME', 'IE_GROUP', 'IE_SEASON', 'IE_EPISODE', 'IE_IS_ID', 'IE_UPDATE', 'IE_DURATION', 'IE_LINK', 'IE_TVG_ID', 'IE_TVG_LOGO', 'IE_TVG_NAME', 'IE_TVG_ATTR', 'IE_LOCALE']
    __tablename__        = 'episode'
    IE_ID                = API.db.Column( "ie_id", API.db.Integer, autoincrement = True, primary_key = True )
    IE_NAME              = API.db.Column( "ie_name", API.db.String( 64 ), nullable = False )
    IE_GROUP             = API.db.Column( "ie_group", API.db.String( 64 ), nullable = False )
    IE_SEASON            = API.db.Column( "ie_season", API.db.Integer, nullable = False )
    IE_EPISODE           = API.db.Column( "ie_episode", API.db.Integer, nullable = False )
    IE_IS_ID             = API.db.Column( "ie_is_id", API.db.Integer, API.db.ForeignKey( "serie.is_id" ), nullable = False )
    IE_UPDATE            = API.db.Column( "ie_update", API.db.DateTime, nullable = True )
    IE_DURATION          = API.db.Column( "ie_duration", API.db.Integer, nullable = True )
    IE_LINK              = API.db.Column( "ie_link", API.db.String( 255 ), nullable = False )
    IE_TVG_ID            = API.db.Column( "ie_tvg_id", API.db.String( 64 ), nullable = True )
    IE_TVG_LOGO          = API.db.Column( "ie_tvg_logo", API.db.LONGTEXT, nullable = True )
    IE_TVG_NAME          = API.db.Column( "ie_tvg_name", API.db.String( 64 ), nullable = True )
    IE_TVG_ATTR          = API.db.Column( "ie_tvg_attr", API.db.LONGTEXT, nullable = True )
    IE_LOCALE            = API.db.Column( "ie_locale", API.db.String( 5 ), nullable = True )

    IE_IS_ID_FK          = API.db.relationship( 'Serie', backref = 'episode', lazy = True )

    def memoryInstance( self ):
        return EpisodeMemory( self )


API.dbtables.register( Episode )


class EpisodeMemory( DbBaseMemory ):
    __model_cls__       = Episode
    __tablename__       = 'episode'


API.memorytables.register( EpisodeMemory )
