#
#   Python backend and Angular frontend code generation by gencrud
#   Copyright (C) 2018-2021 Marc Bertens-Nguyen m.bertens@pe2mbs.nl
#
#   This library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU Library General Public License GPL-2.0-only
#   as published by the Free Software Foundation.
#
#   This library is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Library General Public License for more details.
#
#   You should have received a copy of the GNU Library General Public
#   License GPL-2.0-only along with this library; if not, write to the
#   Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#   Boston, MA 02110-1301 USA
#
#   gencrud: 2022-04-10 21:02:18 version 3.0.685 by user mbertens
#
import webapp2.api as API
from marshmallow import fields, pre_load, post_dump
from webapp2.common.convert import value2Label, utcDateString2Local


class EpisodeSchema( API.mm.SQLAlchemySchema ):
    """Schema for the episode table, this is generated by the gencrud.py module
    When modifing the file make sure that you remove the table from the configuration.
    """
    IE_ID    = fields.Integer()
    IE_NAME    = fields.String()
    IE_GROUP    = fields.String()
    IE_SEASON    = fields.Integer()
    IE_EPISODE    = fields.Integer()
    IE_IS_ID    = fields.Integer()
    IE_IS_ID_FK             = API.mm.Nested( 'SerieSchema' )
    IE_UPDATE    = fields.DateTime()
    IE_DURATION    = fields.Integer()
    IE_LINK    = fields.String()
    IE_TVG_ID    = fields.String()
    IE_TVG_LOGO    = fields.String()
    IE_TVG_NAME    = fields.String()
    IE_TVG_ATTR    = fields.String()
    IE_LOCALE    = fields.String()

    __field_set__ = {
        'IE_ID': 0,
        'IE_NAME': '',
        'IE_GROUP': '',
        'IE_SEASON': 0,
        'IE_EPISODE': 0,
        'IE_IS_ID': 0,
        'IE_UPDATE': '',
        'IE_DURATION': 0,
        'IE_LINK': '',
        'IE_TVG_ID': '',
        'IE_TVG_LOGO': '',
        'IE_TVG_NAME': '',
        'IE_TVG_ATTR': '',
        'IE_LOCALE': '',
    }

    @post_dump
    def post_dump_process( self, in_data, **kwargs ):
        for field, default in self.__field_set__.items():
            if in_data[ field ] is None:
                in_data[ field ] = default

        return in_data

    @pre_load
    def pre_load_process( self, out_data, **kwargs ):
        out_data[ 'IE_UPDATE' ] = utcDateString2Local( out_data[ 'IE_UPDATE' ], '%Y-%m-%d %H:%M:%S' )
        return out_data


episodeSchema   = EpisodeSchema()
episodesSchema  = EpisodeSchema( many = True )

