# Generated by gencrud
# field channel.IC_ENABLED constants
C_IC_ENABLED_YES                                                = True
C_IC_ENABLED_NO                                                 = False

C_IC_ENABLED_MAPPING = {True: 'Yes', False: 'No'}


