#
#   Python backend and Angular frontend code generation by gencrud
#   Copyright (C) 2018-2021 Marc Bertens-Nguyen m.bertens@pe2mbs.nl
#
#   This library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU Library General Public License GPL-2.0-only
#   as published by the Free Software Foundation.
#
#   This library is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Library General Public License for more details.
#
#   You should have received a copy of the GNU Library General Public
#   License GPL-2.0-only along with this library; if not, write to the
#   Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#   Boston, MA 02110-1301 USA
#
#   gencrud: 2022-04-10 21:02:17 version 3.0.685 by user mbertens
#
import webapp2.api as API
from webapp2.common.dbmem import DbBaseMemory
from webapp2.common.crudmixin import CrudModelMixin




class Channel( API.db.Model, CrudModelMixin ):
    """Model for the channel table, this is generated by the gencrud.py module
    When modifing the file make sure that you remove the table from the configuration.
    """
    __field_list__       = ['IC_ID', 'IC_ENABLED', 'IC_NAME', 'IC_ALIAS', 'IC_IB_ID', 'IC_INDEX', 'IC_UPDATE', 'IC_DURATION', 'IC_LINK', 'IC_TVG_ID', 'IC_TVG_LOGO', 'IC_TVG_NAME', 'IC_TVG_ATTR', 'IC_LOCALE']
    __tablename__        = 'channel'
    IC_ID                = API.db.Column( "ic_id", API.db.Integer, autoincrement = True, primary_key = True )
    IC_ENABLED           = API.db.Column( "ic_enabled", API.db.Boolean, default = False )
    IC_NAME              = API.db.Column( "ic_name", API.db.String( 64 ), nullable = False )
    IC_ALIAS             = API.db.Column( "ic_alias", API.db.String( 64 ), nullable = True )
    IC_IB_ID             = API.db.Column( "ic_ib_id", API.db.Integer, API.db.ForeignKey( "bouget.ib_id" ), nullable = False )
    IC_INDEX             = API.db.Column( "ic_index", API.db.Integer, default = 9999 )
    IC_UPDATE            = API.db.Column( "ic_update", API.db.DateTime, nullable = True )
    IC_DURATION          = API.db.Column( "ic_duration", API.db.Integer, nullable = True )
    IC_LINK              = API.db.Column( "ic_link", API.db.String( 255 ), nullable = False )
    IC_TVG_ID            = API.db.Column( "ic_tvg_id", API.db.String( 64 ), nullable = True )
    IC_TVG_LOGO          = API.db.Column( "ic_tvg_logo", API.db.LONGTEXT, nullable = True )
    IC_TVG_NAME          = API.db.Column( "ic_tvg_name", API.db.String( 64 ), nullable = True )
    IC_TVG_ATTR          = API.db.Column( "ic_tvg_attr", API.db.LONGTEXT, nullable = True )
    IC_LOCALE            = API.db.Column( "ic_locale", API.db.String( 5 ), nullable = True )

    IC_IB_ID_FK          = API.db.relationship( 'Bouget', backref = 'channel', lazy = True )

    def memoryInstance( self ):
        return ChannelMemory( self )


API.dbtables.register( Channel )


class ChannelMemory( DbBaseMemory ):
    __model_cls__       = Channel
    __tablename__       = 'channel'


API.memorytables.register( ChannelMemory )
