#
#   Python backend and Angular frontend code generation by gencrud
#   Copyright (C) 2018-2021 Marc Bertens-Nguyen m.bertens@pe2mbs.nl
#
#   This library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU Library General Public License GPL-2.0-only
#   as published by the Free Software Foundation.
#
#   This library is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Library General Public License for more details.
#
#   You should have received a copy of the GNU Library General Public
#   License GPL-2.0-only along with this library; if not, write to the
#   Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#   Boston, MA 02110-1301 USA
#
#   gencrud: 2022-04-10 21:02:17 version 3.0.685 by user mbertens
#
import webapp2.api as API
from marshmallow import fields, pre_load, post_dump
from webapp2.common.convert import value2Label, utcDateString2Local


class ChannelSchema( API.mm.SQLAlchemySchema ):
    """Schema for the channel table, this is generated by the gencrud.py module
    When modifing the file make sure that you remove the table from the configuration.
    """
    IC_ID    = fields.Integer()
    IC_ENABLED    = fields.Boolean()
    IC_NAME    = fields.String()
    IC_ALIAS    = fields.String()
    IC_IB_ID    = fields.Integer()
    IC_IB_ID_FK             = API.mm.Nested( 'BougetSchema' )
    IC_INDEX    = fields.Integer()
    IC_UPDATE    = fields.DateTime()
    IC_DURATION    = fields.Integer()
    IC_LINK    = fields.String()
    IC_TVG_ID    = fields.String()
    IC_TVG_LOGO    = fields.String()
    IC_TVG_NAME    = fields.String()
    IC_TVG_ATTR    = fields.String()
    IC_LOCALE    = fields.String()

    __field_set__ = {
        'IC_ID': 0,
        'IC_ENABLED': 0,
        'IC_NAME': '',
        'IC_ALIAS': '',
        'IC_IB_ID': 0,
        'IC_INDEX': 0,
        'IC_UPDATE': '',
        'IC_DURATION': 0,
        'IC_LINK': '',
        'IC_TVG_ID': '',
        'IC_TVG_LOGO': '',
        'IC_TVG_NAME': '',
        'IC_TVG_ATTR': '',
        'IC_LOCALE': '',
    }

    @post_dump
    def post_dump_process( self, in_data, **kwargs ):
        for field, default in self.__field_set__.items():
            if in_data[ field ] is None:
                in_data[ field ] = default

        in_data[ 'IC_ENABLED_LABEL' ] = value2Label( {True: 'Yes', False: 'No'}, in_data[ 'IC_ENABLED' ] )
        return in_data

    @pre_load
    def pre_load_process( self, out_data, **kwargs ):
        out_data[ 'IC_UPDATE' ] = utcDateString2Local( out_data[ 'IC_UPDATE' ], '%Y-%m-%d %H:%M:%S' )
        return out_data


channelSchema   = ChannelSchema()
channelsSchema  = ChannelSchema( many = True )

