#
#   Python backend and Angular frontend code generation by gencrud
#   Copyright (C) 2018-2021 Marc Bertens-Nguyen m.bertens@pe2mbs.nl
#
#   This library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU Library General Public License GPL-2.0-only
#   as published by the Free Software Foundation.
#
#   This library is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Library General Public License for more details.
#
#   You should have received a copy of the GNU Library General Public
#   License GPL-2.0-only along with this library; if not, write to the
#   Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#   Boston, MA 02110-1301 USA
#
#   gencrud: 2021-04-04 08:26:08 version 2.1.680 by user mbertens
#
import webapp2.api as API
from webapp2.common.dbmem import DbBaseMemory
from webapp2.common.crudmixin import CrudModelMixin




class Languages( API.db.Model, CrudModelMixin ):
    """Model for the languages table, this is generated by the gencrud.py module
    When modifing the file make sure that you remove the table from the configuration.
    """
    __field_list__       = ['LA_ID', 'LA_LABEL', 'LA_CODE2', 'LA_CODE3', 'LA_COUNTRY_CODE2', 'LA_COUNTRY_CODE3']
    __tablename__        = 'language'
    LA_ID                = API.db.Column( "la_id", API.db.Integer, autoincrement = True, primary_key = True )
    LA_LABEL             = API.db.Column( "la_label", API.db.String( 30 ), nullable = False )
    LA_CODE2             = API.db.Column( "la_code2", API.db.String( 2 ), nullable = False )
    LA_CODE3             = API.db.Column( "la_code3", API.db.String( 3 ), nullable = False )
    LA_COUNTRY_CODE2     = API.db.Column( "la_country_code2", API.db.String( 2 ), nullable = False )
    LA_COUNTRY_CODE3     = API.db.Column( "la_country_code3", API.db.String( 3 ), nullable = False )

    API.db.UniqueConstraint( 'LA_LABEL', name='LA_LABEL_IDX' )
    API.db.UniqueConstraint( 'LA_CODE2', name='LA_CODE2_IDX' )
    API.db.UniqueConstraint( 'LA_CODE3', name='LA_CODE3_IDX' )
    API.db.UniqueConstraint( 'LA_COUNTRY_CODE2', name='LA_COUNTRY_CODE2_IDX' )
    API.db.UniqueConstraint( 'LA_COUNTRY_CODE3', name='LA_COUNTRY_CODE3_IDX' )
    LANGUAGE_REFERENCE_relation       = API.db.relationship( "LanguageReference", cascade="delete,all", backref = 'language', lazy = True )

    def memoryInstance( self ):
        return LanguagesMemory( self )


API.dbtables.register( Languages )


class LanguagesMemory( DbBaseMemory ):
    __model_cls__       = Languages
    __tablename__       = 'language'


API.memorytables.register( LanguagesMemory )
