"""empty message

Revision ID: R2021_01
Revises: 
Create Date: 2021-10-22 21:46:19.066389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'R2021_01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BOUGET',
    sa.Column('b_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('b_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('b_id')
    )
    op.create_table('M3U',
    sa.Column('m3_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('m3_runtime', sa.Integer(), nullable=False),
    sa.Column('m3_title', sa.String(length=60), nullable=False),
    sa.Column('m3_link', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('m3_id')
    )
    op.create_table('CHANNEL',
    sa.Column('c_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_name', sa.String(length=60), nullable=False),
    sa.Column('c_enabled', sa.Boolean(), nullable=False),
    sa.Column('c_b_id', sa.Integer(), nullable=False),
    sa.Column('c_m3_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['c_b_id'], ['BOUGET.b_id'], ),
    sa.ForeignKeyConstraint(['c_m3_id'], ['M3U.m3_id'], ),
    sa.PrimaryKeyConstraint('c_id')
    )
    op.create_table('M3U_ATTR',
    sa.Column('ma_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ma_m3u_id', sa.Integer(), nullable=False),
    sa.Column('ma_attribute', sa.String(length=20), nullable=False),
    sa.Column('ma_value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ma_m3u_id'], ['M3U.m3_id'], ),
    sa.PrimaryKeyConstraint('ma_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('M3U_ATTR')
    op.drop_table('CHANNEL')
    op.drop_table('M3U')
    op.drop_table('BOUGET')
    # ### end Alembic commands ###
