# Generated by gencrud
# field m3u_attr.MA_OVERIDE constants
C_MA_OVERIDE_NO_OVERRIDE                                        = 0
C_MA_OVERIDE_CHANNEL_TITLE                                      = 1
C_MA_OVERIDE_BOUGET_NAME                                        = 2

C_MA_OVERIDE_MAPPING = {0: 'No override', 1: 'Channel title', 2: 'Bouget name'}


