#
#   Python backend and Angular frontend code generation by gencrud
#   Copyright (C) 2018-2021 Marc Bertens-Nguyen m.bertens@pe2mbs.nl
#
#   This library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU Library General Public License GPL-2.0-only
#   as published by the Free Software Foundation.
#
#   This library is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Library General Public License for more details.
#
#   You should have received a copy of the GNU Library General Public
#   License GPL-2.0-only along with this library; if not, write to the
#   Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#   Boston, MA 02110-1301 USA
#
#   gencrud: 2021-10-24 19:21:03 version 3.0.685 by user mbertens
#
import webapp2.api as API
from webapp2.common.dbmem import DbBaseMemory
from webapp2.common.crudmixin import CrudModelMixin




class M3uAttr( API.db.Model, CrudModelMixin ):
    """Model for the m3u_attr table, this is generated by the gencrud.py module
    When modifing the file make sure that you remove the table from the configuration.
    """
    __field_list__       = ['MA_ID', 'MA_ATTRIBUTE', 'MA_VALUE', 'MA_M_ID', 'MA_OVERIDE']
    __tablename__        = 'm3u_attr'
    MA_ID                = API.db.Column( "ma_id", API.db.Integer, autoincrement = True, primary_key = True )
    MA_ATTRIBUTE         = API.db.Column( "ma_attribute", API.db.String( 30 ), nullable = False )
    MA_VALUE             = API.db.Column( "ma_value", API.db.String( 255 ), nullable = False )
    MA_M_ID              = API.db.Column( "ma_m_id", API.db.Integer, API.db.ForeignKey( "m3u.m_id" ), nullable = False )
    MA_OVERIDE           = API.db.Column( "ma_overide", API.db.Integer, default = 0 )

    MA_M_ID_FK           = API.db.relationship( 'M3u', backref = 'm3u_attr', lazy = True )

    def memoryInstance( self ):
        return M3uAttrMemory( self )


API.dbtables.register( M3uAttr )


class M3uAttrMemory( DbBaseMemory ):
    __model_cls__       = M3uAttr
    __tablename__       = 'm3u_attr'


API.memorytables.register( M3uAttrMemory )
