#
#   Python backend and Angular frontend code generation by gencrud
#   Copyright (C) 2018-2021 Marc Bertens-Nguyen m.bertens@pe2mbs.nl
#
#   This library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU Library General Public License GPL-2.0-only
#   as published by the Free Software Foundation.
#
#   This library is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Library General Public License for more details.
#
#   You should have received a copy of the GNU Library General Public
#   License GPL-2.0-only along with this library; if not, write to the
#   Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#   Boston, MA 02110-1301 USA
#
#   gencrud: 2022-04-10 21:02:18 version 3.0.685 by user mbertens
#
import webapp2.api as API
from webapp2.common.dbmem import DbBaseMemory
from webapp2.common.crudmixin import CrudModelMixin




class Replace( API.db.Model, CrudModelMixin ):
    """Model for the replace table, this is generated by the gencrud.py module
    When modifing the file make sure that you remove the table from the configuration.
    """
    __field_list__       = ['IR_ID', 'IR_FIND', 'IR_REPLACE']
    __tablename__        = 'replace'
    IR_ID                = API.db.Column( "ir_id", API.db.Integer, autoincrement = True, primary_key = True )
    IR_FIND              = API.db.Column( "ir_find", API.db.String( 128 ), nullable = False )
    IR_REPLACE           = API.db.Column( "ir_replace", API.db.String( 128 ), nullable = False )


    def memoryInstance( self ):
        return ReplaceMemory( self )


API.dbtables.register( Replace )


class ReplaceMemory( DbBaseMemory ):
    __model_cls__       = Replace
    __tablename__       = 'replace'


API.memorytables.register( ReplaceMemory )
