# Generated by gencrud
# field config.IF_ENABLED constants
C_IF_ENABLED_YES                                                = True
C_IF_ENABLED_NO                                                 = False

C_IF_ENABLED_MAPPING = {True: 'Yes', False: 'No'}


# field config.IF_AUTH constants
C_IF_AUTH_NO_AUTHENTICATION                                  = 0
C_IF_AUTH_BASIC_AUTHENTICATION                               = 1
C_IF_AUTH_DIGEST_AUTHENTICATION                              = 2

C_IF_AUTH_MAPPING = {0: 'No authentication', 1: 'Basic authentication', 2: 'Digest authentication'}


