#
#   Python backend and Angular frontend code generation by gencrud
#   Copyright (C) 2018-2021 Marc Bertens-Nguyen m.bertens@pe2mbs.nl
#
#   This library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU Library General Public License GPL-2.0-only
#   as published by the Free Software Foundation.
#
#   This library is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Library General Public License for more details.
#
#   You should have received a copy of the GNU Library General Public
#   License GPL-2.0-only along with this library; if not, write to the
#   Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#   Boston, MA 02110-1301 USA
#
#   gencrud: 2022-04-10 21:02:17 version 3.0.685 by user mbertens
#
import webapp2.api as API
from marshmallow import fields, pre_load, post_dump
from webapp2.common.convert import value2Label, utcDateString2Local


class ConfigSchema( API.mm.SQLAlchemySchema ):
    """Schema for the config table, this is generated by the gencrud.py module
    When modifing the file make sure that you remove the table from the configuration.
    """
    IF_ID    = fields.Integer()
    IF_ENABLED    = fields.Boolean()
    IF_NAME    = fields.String()
    IF_LOCATION    = fields.String()
    IF_USERNAME    = fields.String()
    IF_PASSWORD    = fields.String()
    IF_AUTH    = fields.Integer()

    __field_set__ = {
        'IF_ID': 0,
        'IF_ENABLED': 0,
        'IF_NAME': '',
        'IF_LOCATION': '',
        'IF_USERNAME': '',
        'IF_PASSWORD': '',
        'IF_AUTH': 0,
    }

    @post_dump
    def post_dump_process( self, in_data, **kwargs ):
        for field, default in self.__field_set__.items():
            if in_data[ field ] is None:
                in_data[ field ] = default

        in_data[ 'IF_ENABLED_LABEL' ] = value2Label( {True: 'Yes', False: 'No'}, in_data[ 'IF_ENABLED' ] )
        in_data[ 'IF_AUTH_LABEL' ] = value2Label( {0: 'No authentication', 1: 'Basic authentication', 2: 'Digest authentication'}, in_data[ 'IF_AUTH' ] )
        return in_data

    @pre_load
    def pre_load_process( self, out_data, **kwargs ):
        return out_data


configSchema   = ConfigSchema()
configsSchema  = ConfigSchema( many = True )

