#
#   Python backend and Angular frontend code generation by gencrud
#   Copyright (C) 2018-2021 Marc Bertens-Nguyen m.bertens@pe2mbs.nl
#
#   This library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU Library General Public License GPL-2.0-only
#   as published by the Free Software Foundation.
#
#   This library is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Library General Public License for more details.
#
#   You should have received a copy of the GNU Library General Public
#   License GPL-2.0-only along with this library; if not, write to the
#   Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#   Boston, MA 02110-1301 USA
#
#   gencrud: 2022-04-10 21:02:17 version 3.0.685 by user mbertens
#
import webapp2.api as API
from webapp2.common.dbmem import DbBaseMemory
from webapp2.common.crudmixin import CrudModelMixin




class Alias( API.db.Model, CrudModelMixin ):
    """Model for the alias table, this is generated by the gencrud.py module
    When modifing the file make sure that you remove the table from the configuration.
    """
    __field_list__       = ['IA_ID', 'IA_NAME', 'IA_ALIAS', 'IA_INDEX']
    __tablename__        = 'alias'
    IA_ID                = API.db.Column( "ia_id", API.db.Integer, autoincrement = True, primary_key = True )
    IA_NAME              = API.db.Column( "ia_name", API.db.String( 64 ), nullable = False )
    IA_ALIAS             = API.db.Column( "ia_alias", API.db.String( 64 ), nullable = False )
    IA_INDEX             = API.db.Column( "ia_index", API.db.Integer, nullable = True )


    def memoryInstance( self ):
        return AliasMemory( self )


API.dbtables.register( Alias )


class AliasMemory( DbBaseMemory ):
    __model_cls__       = Alias
    __tablename__       = 'alias'


API.memorytables.register( AliasMemory )
