# Generated by gencrud
# field bouget.IB_ENABLED constants
C_IB_ENABLED_YES                                                = True
C_IB_ENABLED_NO                                                 = False

C_IB_ENABLED_MAPPING = {True: 'Yes', False: 'No'}


